### ISSUE TITLE
Вопрос на засыпку

### ISSUE THREAD

**Issue by etihtech** [NC22/HTML5-HSL-Color-Multi-Select#1]
Привет, не придумал как с тобой можно ещё связаться. У тебя давным давно был блог (вроде по адресу catface.ru) на котором ты использовал очень минималистичный шаблон. Не подскажешь название? Напиши на felant1999@gmail.com

**Comment by NC22** [comment]
Прив. Да можешь скайп добавить torrenttvi. Переехал, а сервер после переезда пока негде разместить, вот сайт и офлайн. 

Если тот который в темнофиолетовых оттенках, то это был сайт с переделанным webMCR , с моим простеньким шаблоном который от бутстрапа унаследовал сетку. Короче не помню чтобы там какие-то готовые решения были да и нигде не размещал открыто потом. Если нужно могу кинуть как-нибудь на гитхаб ту кастомизированную под блог версию движка. Или напиши для каких целей, кину что то отдельно если нужно.
